@extends('frontend.layouts.web')
@section('frontend_header')
    <meta property="og:title" content="Xoss Games | Enjoy a Wide Range of Online Games on Xoss Games">
    <meta property="og:description" content="Xoss Games | Enjoy a Wide Range of Online Games on Xoss Games">
    <meta property="og:image" content="https://xoss.games/xoss_games-og-image.jpg" />
    <meta property="og:url" content="https://xoss.games/">
    <meta name="title" content="Play Online Games on Xoss Games - Your Ultimate Gaming Destination" />
    <meta name="description"
        content="Looking for a thrilling gaming experience? Xoss Games offers a wide range of online games to play for free. Get ready for hours of fun and excitement on our gaming platform!" />
    <meta name="keywords"
        content="Online games, Play games online,Free online games,Xoss games	,Best online games,Play free online games,Multiplayer games,Play online games for free,Online shooting games,Online,puzzle games,Play free games online,Play online multiplayer games ,Online action games	,Best free online games,Online adventure games,Online strategy games Play online action games" />
    <link rel="canonical" href="https://xoss.games" />
    <title>PlayToony | Play online Games on Playtoony</title>
@endsection
@section('content')

{{-- banner gradient --}}
<div class="backwrap gradient">
    <div class="back-shapes">
        <!-- All this img tags was autogenerated by custom written js tool -->
        <span class="floating circle" style="top:66.59856996935649%;left:13.020833333333334%;animation-delay:-0.9s;"></span>
        <span class="floating triangle" style="top:31.46067415730337%;left:33.59375%;animation-delay:-4.8s;"></span>
        <span class="floating cross" style="top:76.50663942798774%;left:38.020833333333336%;animation-delay:-4s;"></span>
        <span class="floating square" style="top:21.450459652706844%;left:14.0625%;animation-delay:-2.8s;"></span>
        <span class="floating square" style="top:58.12053115423902%;left:56.770833333333336%;animation-delay:-2.15s;"></span>
        <span class="floating square" style="top:8.682328907048008%;left:72.70833333333333%;animation-delay:-1.9s;"></span>
        <span class="floating cross" style="top:31.3585291113381%;left:58.541666666666664%;animation-delay:-0.65s;"></span>
        <span class="floating cross" style="top:69.96935648621042%;left:81.45833333333333%;animation-delay:-0.4s;"></span>
        <span class="floating circle" style="top:15.117466802860061%;left:32.34375%;animation-delay:-4.1s;"></span>
        <span class="floating circle" style="top:13.074565883554648%;left:45.989583333333336%;animation-delay:-3.65s;"></span>
        <span class="floating cross" style="top:55.87334014300306%;left:27.135416666666668%;animation-delay:-2.25s;"></span>
        <span class="floating cross" style="top:49.54034729315628%;left:53.75%;animation-delay:-2s;"></span>
        <span class="floating cross" style="top:34.62717058222676%;left:49.635416666666664%;animation-delay:-1.55s;"></span>
        <span class="floating cross" style="top:33.19713993871297%;left:86.14583333333333%;animation-delay:-0.95s;"></span>
        <span class="floating square" style="top:28.19203268641471%;left:25.208333333333332%;animation-delay:-4.45s;"></span>
        <span class="floating circle" style="top:39.7344228804903%;left:10.833333333333334%;animation-delay:-3.35s;"></span>
        <span class="floating triangle" style="top:77.83452502553627%;left:24.427083333333332%;animation-delay:-2.3s;"></span>
        <span class="floating triangle" style="top:2.860061287027579%;left:47.864583333333336%;animation-delay:-1.75s;"></span>
        <span class="floating triangle" style="top:71.3993871297242%;left:66.45833333333333%;animation-delay:-1.25s;"></span>
        <span class="floating triangle" style="top:31.256384065372828%;left:76.92708333333333%;animation-delay:-0.65s;"></span>
        <span class="floating triangle" style="top:46.47599591419816%;left:38.90625%;animation-delay:-0.35s;"></span>
        <span class="floating cross" style="top:3.4729315628192032%;left:19.635416666666668%;animation-delay:-4.3s;"></span>
        <span class="floating cross" style="top:3.575076608784474%;left:6.25%;animation-delay:-4.05s;"></span>
        <span class="floating cross" style="top:77.3237997957099%;left:4.583333333333333%;animation-delay:-3.75s;"></span>
        <span class="floating cross" style="top:0.9193054136874361%;left:71.14583333333333%;animation-delay:-3.3s;"></span>
        <span class="floating square" style="top:23.6976506639428%;left:63.28125%;animation-delay:-2.1s;"></span>
        <span class="floating square" style="top:81.30745658835546%;left:45.15625%;animation-delay:-1.75s;"></span>
        <span class="floating square" style="top:60.9805924412666%;left:42.239583333333336%;animation-delay:-1.45s;"></span>
        <span class="floating square" style="top:29.009193054136876%;left:93.90625%;animation-delay:-1.05s;"></span>
        <span class="floating square" style="top:52.093973442288046%;left:68.90625%;animation-delay:-0.7s;"></span>
        <span class="floating square" style="top:81.51174668028601%;left:83.59375%;animation-delay:-0.35s;"></span>
        <span class="floating square" style="top:11.542390194075587%;left:91.51041666666667%;animation-delay:-0.1s;"></span>
    </div>
  </div>
{{-- banner gradient --}}

    <!-- --------------------------bannar start ---------------------- -->
    <header class="bannar">
        <div class="bannar__body">
            <div class="bannar__body__text container ">
                <div class="content">
                    <h2 class="heading" data-text="Game Baksho">Game Baksho</h2>
                    <p class="bannar__body__text__description animate-pop-in">
                        Play all exciting games
                        <br>
                        in one subscription
                    </p>
                    @if (!$subscribed)
                        <div class="bannar__body__btn shake" id="interact_btn">
                            @if (!$isMobile)
                                {{-- <button class="btn__hover pulse" data-toggle="modal" data-target="#subscription_pop">Subscribe
                                    Now</button> --}}
                                <button class="btn__hover pulse">Subscribe
                                    Now</button>
                            @else
                                {{-- <a href="{{ route('user.packages') }}"> <button class="btn__hover pulse">Subscribe
                                        Now</button></a> --}}
                                <a href="#"> <button class="btn__hover pulse">Subscribe
                                        Now</button></a>
                            @endif
                        </div>
                    @endif
                  </div>
                
            
            </div>
        </div>
    </header>
    <!-- --------------------------bannar end ------------------------ -->




    

    <!-- --------------------------PRELOADER START ------------------------ -->
    <div id="preloader_container">
        <div class="preloader">
            <div class="content bannar__body__text">
                <h2 class="heading" data-text="Game Baksho">Game Baksho</h2>
            </div>
            <div class="preload_box"></div>
        </div>
    </div>
    <!-- --------------------------PRELOADER END ------------------------ -->
    <!-- --------------------------subscribe for all game/mostPopular start ----->
    <section class="mostPopular lock" id="allGame">
        <div class="container">

            <div class="mostPopular__title mb-3 mb-md-5">
                @if (!$subscribed)
                    <h2
                        class="mostPopular__title__text mostPopular__title__text--font-width mostPopular__title__text--font-size">
                        {{-- Subscribe <span>to Play</span> --}}
                    </h2>
                @endif
                @if($subscribed)
                <h2 class="mostPopular__title__text mostPopular__title__text--font-size mt-5">
                  <img
                        src="{{ asset('assets/frontend/img/coding.png') }}" alt="">  All Games
                </h2>
                @else
                <h2 class="mostPopular__title__text mostPopular__title__text--font-size mt-5">
                    <img
                        src="{{ asset('assets/frontend/img/premium.png') }}" height="40px" width="40px" alt=""> Exclusive Games
                </h2>
                @endif
                <p class="subheading_common">From puzzles to action, adventure to sports, we offer a vast collection of
                    online games for all ages</p>
            </div>
            <div class="card__wrapper row justify-content-center">
                @foreach ($notFreeGames as $game)
                    <div class=" col-6 col-sm-6 col-md-4 col-lg-4 col-xl-3 p-0">
                        <a href="{{ route('game', $game->game_file) }}">
                          
                            <div class="card card__body">
                                <!-- <div class="premium_badge">Premium <span class="premium_icon"><i class="fa-solid fa-crown"></i></span> </div>-->
                                <img src="{{ asset('assets/frontend/images/uploads/games_img/' . $game->game_thumbnail) }}"
                                    width="220" height="210" class="card-img-top card__img"
                                    alt="{{ $game->game_thumbnail }}" />
                                <div class="card-body card__text__body">
                                    <h3 class="card-title card__text">{{ Str::limit($game->game_name, 17, '...') }}</h3>
                                </div>
                                @if (!$subscribed)
                                
                                <div class="premium_badge">
                                    <img src="{{ asset('assets/frontend/img/premium_game.png') }}" alt="">
                                </div>
                                    
                                @endif
                            </div>
                        </a>
                    </div>
                @endforeach
            </div>
        </div>
        </div>
    </section>
    <!-- --------------------------subscribe for all game/mostPopular end-------------------- -->
    <!-- ------------------------- Exclusive Games Trailers Start ---------------------->
    <section class="slider" id="youTube">
        <div class="container">
            <div class="row section__header">
                <div class="mostPopular__title col-12 mb-3 mb-md-5">
                    <h3 class="mostPopular__title__text mostPopular__title__text--font-size">
                     <img
                        src="{{ asset('assets/frontend/img/treasers.png') }}" height="40px" width="40px" alt="">   Latest Game Teasers
                    </h3>
                    <p class="subheading_common"> An opportunity to stay informed about the latest and upcoming games
                        through teasers and trailers</p>
                </div>
            </div>
            <div class="row slider__items">
                <div class="col-xl-3 col-lg-4 col-md-6  col-sm-12">
                    <div class="card__height">
                        <a data-fancybox="gallery" class="slider__item hover1 popup-youtube"
                            href="https://youtu.be/VIK-6oNij3U?list=PLniueHXS3q--oX21mZaRXSHL2PWnH-cmV" target="blank">
                            <img class="slider__item--banner"
                                src="{{ asset('assets/frontend/img/animal-match-master.webp') }}" alt="" />

                            <div class="play_icon"> <i class="fa-solid fa-play"></i></div>

                            <div class="slider__card__title slidr__card__title--position col-12">
                                <h4 class="slider__card__title__text">Animal Match Master</h4>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 col-md-6  col-sm-12">
                    <div class="card__height">
                        <a data-fancybox="gallery" class="slider__item hover2"
                            href="https://youtu.be/hxR5FN244Yg?list=PLniueHXS3q--oX21mZaRXSHL2PWnH-cmV">
                            <img class="slider__item--banner"
                                src="{{ asset('assets/frontend/img/football-color-matcher-320x240.webp') }}"
                                alt="" />
                            <div class="play_icon"> <i class="fa-solid fa-play"></i></div>
                            <div class="slider__card__title col-12">
                                <h4 class="slider__card__title__text">Football Color Matcher</h4>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 col-md-6  col-sm-12">
                    <div class="card__height">
                        <a data-fancybox="gallery" class="slider__item hover3"
                            href="https://youtu.be/jDHbzOENFK0?list=PLniueHXS3q--oX21mZaRXSHL2PWnH-cmV">
                            <img class="slider__item--banner"
                                src="{{ asset('assets/frontend/img/space-challenge-320x240.webp') }}" alt="" />
                            <div class="play_icon"> <i class="fa-solid fa-play"></i></div>
                            <div class="slider__card__title slidr__card__title--position col-12">
                                <h4 class="slider__card__title__text">Space Challenge</h4>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 col-md-6  col-sm-12">
                    <div class="card__height">
                        <a data-fancybox="gallery" class="slider__item hover4"
                            href="https://youtu.be/dhy4mf-Ik5E?list=PLniueHXS3q--oX21mZaRXSHL2PWnH-cmV">
                            <img class="slider__item--banner"
                                src="{{ asset('assets/frontend/img/fluffy-rush-320x240.webp') }}" alt="" />
                            <div class="play_icon"> <i class="fa-solid fa-play"></i></div>
                            <div class="slider__card__title slidr__card__title--position col-12">
                                <h4 class="slider__card__title__text">Fluffy Rush</h4>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 col-md-6  col-sm-12">
                    <div class="card__height">
                        <a data-fancybox="gallery" class="slider__item hover5"
                            href="https://youtu.be/xRWuWWx0bGc?list=PLniueHXS3q--oX21mZaRXSHL2PWnH-cmV">
                            <img class="slider__item--banner"
                                src="{{ asset('assets/frontend/img/burger-elf-video-thambnail.webp') }}"
                                alt="" />
                            <div class="play_icon"> <i class="fa-solid fa-play"></i></div>
                            <div class="slider__card__title slidr__card__title--position col-12">
                                <h4 class="slider__card__title__text">BURGER ELF</h4>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ------------------------- Exclusive Games Trailers End ---------------------->

        <!-- --------------------------small card start ------------------------ -->
        {{-- <section id="small_card">
            <div class="from_left">
                
            </div>
        </section>
        <section id="small_card">
            <div class="from_right">
    
            </div>
        </section> --}}
        <!-- --------------------------small card end ------------------------ -->

    <!---custom subscriber tracking popup---->
  
    @if (session('subs_success'))
        <div class="subscriber_tracking_success_popup">
            <div id="success_popup" class="success_popup">
                <div class="subscriber_tracking_success_popup_inner active">
                    <div class="popup_info_icon succes_icon">
                        <i class="fa-solid fa-check"></i>
                    </div>
                    <div class="popup_info_text">
                        <h1>Success !</h1>
                        <p>Subscription Successfull! Enjoy our games!</p>
                        <button class="tracking_ok_button" id="{{ session('subs_success') }}" onclick="hidePopup()">OK</button>
                    </div>
                </div>
            </div>
        </div>
    @endif
@endsection
@section('pageJS')
    <script>
        //----custom subscriber success tracking popup----//
        function hidePopup() {
            var popupContainer = document.querySelector(".subscriber_tracking_success_popup");
            popupContainer.classList.add("active");
        }
    </script>
@endsection
